monitor=HDMI-A-2,1920x1080@60,0x0,1,transform,1
monitor=DP-2,2560x1440@120,1080x360,1

exec-once = xrandr --output DP-2 --primary

cursor {
    default_monitor = DP-2
}

workspace = 1, monitor:DP-2, name:λ, default:true
workspace = 2, monitor:DP-2, name:β
workspace = 3, monitor:DP-2, name:γ
workspace = 6, monitor:DP-2, name:Ψ

workspace = 4, monitor:HDMI-A-2, name:δ, default:true
workspace = 5, monitor:HDMI-A-2, name:ε

windowrule {
  name = windowrule-14
  workspace = 5
  monitor = HDMI-A-2
  match:class = ^(discord)$
}

windowrule {
  name = windowrule-15
  workspace = 5
  monitor = HDMI-A-2
  match:class = ^(teams-for-linux)$
}

bind = SUPER ALT, S, moveworkspacetomonitor, current HDMI-A-2
bind = SUPER ALT, D, moveworkspacetomonitor, current DP-2
