monitor=eDP-1,preferred,auto,1

cursor {
    default_monitor = eDP-1
}

workspace = 1, monitor:eDP-1, name:λ, default:true
workspace = 2, monitor:eDP-1, name:β
workspace = 3, monitor:eDP-1, name:γ
workspace = 4, monitor:eDP-1, name:δ
workspace = 5, monitor:eDP-1, name:ε
workspace = 6, monitor:eDP-1, name:Ψ

windowrule {
  name = windowrule-14
  workspace = 5
  match:class = ^(discord)$
}

windowrule {
  name = windowrule-15
  workspace = 5
  match:class = ^(teams-for-linux)$
}
