general {
    disable_loading_bar = true
    grace = 5
    hide_cursor = true
    no_fade_in = false
}

background {
    monitor = DP-2
    path = /home/silverest/Pictures/prom4.jpg
    blur_passes = 1
    blur_size = 4
    brightness = 0.5
    contrast = 1.0
}

background {
    monitor = HDMI-A-2
    path = /home/silverest/Pictures/__promeia_zenless_zone_zero_drawn_by_appl3__d86f0acc8b5aebc93a71160bb8620a1c.png
    blur_passes = 1
    blur_size = 4
    brightness = 0.5
    contrast = 1.0
}

input-field {
    monitor = DP-2
    size = 200, 50
    position = 0, -80
    dots_center = true
    fade_on_empty = false
    font_color = rgb(229, 229, 229)
    font_family = FiraCode Nerd Font Mono
    inner_color = rgb(24, 22, 22)
    outer_color = rgb(156, 140, 230)
    outline_thickness = 5
    placeholder_text = <span foreground="##6B7D8C">PWD_</span>
    shadow_passes = 2
}

label {
    monitor = DP-2
    text = TWIT RPENT
    color = rgb(156, 140, 230)
    font_size = 50
    font_family = Makcasa
    position = -62, 8
    halign = right
    valign = bottom
}

shape {
    monitor = DP-2
    size = 2, 154
    color = rgb(156, 140, 230)
    position = -50, 24
    halign = right
    valign = bottom
    rounding = 0
}

label {
    monitor = DP-2
    text = 蛇
    color = rgb(156, 140, 230)
    font_size = 16
    font_family = Noto Sans CJK JP
    position = -20, 24
    halign = right
    valign = bottom
}

label {
    monitor = DP-2
    text = 大
    color = rgb(156, 140, 230)
    font_size = 16
    font_family = Noto Sans CJK JP
    position = -20, 54
    halign = right
    valign = bottom
}

label {
    monitor = DP-2
    text = の
    color = rgb(156, 140, 230)
    font_size = 16
    font_family = Noto Sans CJK JP
    position = -20, 84
    halign = right
    valign = bottom
}

label {
    monitor = DP-2
    text = 昏
    color = rgb(156, 140, 230)
    font_size = 16
    font_family = Noto Sans CJK JP
    position = -20, 114
    halign = right
    valign = bottom
}

label {
    monitor = DP-2
    text = 黄
    color = rgb(156, 140, 230)
    font_size = 16
    font_family = Noto Sans CJK JP
    position = -20, 144
    halign = right
    valign = bottom
}
