splash = false

wallpaper {
    monitor = DP-2
    path = /home/silverest/Pictures/prom4.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-2
    path = /home/silverest/Pictures/calendar/06-cropped.jpg
    fit_mode = cover
}
